# Generated by Django 3.2.5 on 2021-07-07 11:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_areaofinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='observations/')),
                ('obs_date', models.DateTimeField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
