# Generated by Django 3.2.5 on 2021-07-07 11:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_observationtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationtest',
            name='coordinate',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
