# Generated by Django 3.2.5 on 2021-07-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_alter_observationtest_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationtest',
            name='obs_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
