# Generated by Django 3.2.5 on 2021-07-08 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('observations', '0005_alter_observationtest_obs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaofinterest',
            name='scientist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.scientist'),
        ),
        migrations.AddField(
            model_name='observationtest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.citizenscientist'),
        ),
    ]
