# Generated by Django 3.2.5 on 2021-07-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_auto_20210708_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaofinterest',
            name='observations',
            field=models.ManyToManyField(null=True, to='observations.ObservationTest'),
        ),
    ]
