# Generated by Django 3.2.5 on 2021-07-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0008_alter_areaofinterest_observations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observationtest',
            options={'permissions': (('can_upload_observation', 'User allowed to upload observations'),)},
        ),
    ]
