# Generated by Django 3.2.5 on 2021-07-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_challange_users'),
        ('users', '0002_auto_20210720_1131'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='challenges',
            field=models.ManyToManyField(default=[1], to='challenges.Challange'),
        ),
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(blank=True, to='users.CitizenScientist'),
        ),
    ]
